### ISSUE TITLE
Rules not including some shared libraries Qt depends on

### ISSUE THREAD

**Issue by dieortin** [kklochkov/rules_qt#1]
I'm trying to build a small Qt application using this rules in SUSE Linux SLES 15 SP4, and I'm running into the following error message:
` error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory`

It seems like this shared library is not being linked into the binary. My system includes a newer version of the library, but Qt seems to require that specific one, which it includes among its own libraries (`libQt6Core.so`, etc.)

When inspecting the built binary with `ldd`, other two shared libraries seem to be missing:
```
libicui18n.so.56 => not found
libicuuc.so.56 => not found
libicudata.so.56 => not found
```

I've had a look at the `qt_local_repo` implementation, and it seems to create Bazel targets for all libraries starting with `libQt6`, but not for any of the others, so I cannot manually include `@qt//:icui18n` in the `deps` attribute of the `qt_cc_binary` rule (but anyways, if those shared libraries are always a dependency they would be best included by the macro itself I guess)

### Qt binary rule instantiation
In case it helps, here's how I'm creating the binary target inside my `BUILD` file. Some parts are redacted, as I cannot share them.
```
qt_cc_binary(
    name = "redacted-target",
    srcs = [
        "redacted1.cpp",
        "redacted2.cpp",
        "redacted3.h",
        "redacted4.h",
    ],
    moc_hdrs = ["redacted5.hpp"],
    qrc_srcs = [":redacted-qrc"],
    deps = [
        ":redacted",
        "@qt//:QtCore",
        "@qt//:QtDBus",
        "@qt//:QtNetwork",
        "@qt//:QtOpenGL",
        "@qt//:QtQml",
        "@qt//:QtQmlModels",
        "@qt//:QtQuick",
        "@qt//:QtWidgets",
    ],
)
```

Thank you very much in advance, and please let me know if I can be of any help.

**Comment by kklochkov** [comment]
Hey @dieortin!

Thanks for trying out rules and giving some feedback!

It sounds like misconfiguration of Qt. 
Did you try to build and run any Qt examples using `CMake`?

How do you use `qt_local_repo`? Do you use locally installed `Qt` or do you use `qt_http_repo`?

If `qt_local_repo` rule is used to refer to pre-installed `Qt` binaries, then the rule makes `Qt` accessible under `Bazel`, it doesn't try to resolve any run-time dependencies that `Qt` installation requires.

Another option, is to build `Qt` manually (that might take time of course). For that, one needs to use `qt_http_repo` and `qt_local_repo` as shown here: https://github.com/kklochkov/rules_qt/blob/main/examples/WORKSPACE#L88

In both cases following official `Qt`'s installation instructions to full-fill runtime requirements should be performed. So, I would start with that.

**Comment by dieortin** [comment]
I’m porting a Qt application that already builds correctly with CMake to Bazel, and I’m using the same locally installed Qt6 with `qt_local_repo`.

The runtime requirements are there, in the `/lib` folder of the Qt6 installation, next to the `libQt6*.so` libraries, which are correctly made available by the rules. With CMake the entire `/lib` folder is added to `LD_PRELOAD_PATH`, so binaries find the `.so` files without issues.

What I’m struggling to understand is why you don’t have this issue, are your `libicui18n.so` etc. in your system library folder?

**Comment by kklochkov** [comment]
Right, `libicui18n*` is coming from the `sysroot`.
It should be possible to provide `env` variables in `qt_cc_binary` as well (i.e. supply `LD_PRELOAD_PATH ` or `LD_LIBRARY_PATH`). Though, I would rebuild Qt with correct `rpath`.

**Comment by dieortin** [comment]
Ah okay, I thought Qt needed to always be linked against the specific version of `libicui18n.so` and the other libraries that it provides. 

In that case it definitely looks like Qt was linked against that specific version instead of the system one for some reason when it was installed (a misconfiguration like you said)

I will try to reinstall Qt and get it to link against the system provided libraries, and update this issue. 

Thank you very much for your help and for this awesome rules!

**Comment by dieortin** [comment]
I have confirmed the resulting binary can find its dependencies when Qt6 has been installed through my distribution´s package manager, which links against the system version of those libraries. This was indeed an installation error.

Thank you!

**Comment by kklochkov** [comment]
Thanks a lot for checking and letting me know! Cheers!
